name: tarot_bot
description: Telegram bot for launching the Tarot mini-app via WebApp button.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  dotenv: ^4.2.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  teledart: ^0.6.1
  logger: ^2.0.2

dev_dependencies:
  http: ^1.3.0
  lints: ^5.0.0
  mockito: ^5.4.6
  test: ^1.24.0
