name: Deploy Tarot Bot

on:
  push:
    branches:
      - main
    tags:
      - 'v*'      

jobs:
  unit-test:
    name: ✅ Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.7.2'

      - name: Run tests
        run: dart test

  build:
    name: ⚒️ Build Binary
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.7.2'

      - name: Install dependencies
        run: dart pub get

      - name: Compile executable
        run: dart compile exe bin/main.dart -o tarot_bot

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tarot-bot-binary
          path: tarot_bot

  upload:
    name: 🚚 Upload to Server
    runs-on: ubuntu-latest
    needs: build


    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download binary artifact
      uses: actions/download-artifact@v4
      with:
        name: tarot-bot-binary

    - name: Upload binary to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: tarot_bot
        target: ${{ vars.SERVER_PATH }}/
            
  restart:
    name: 🔄 Restart Service (Optional)
    needs: [upload]
    runs-on: ubuntu-latest
    steps:
      - name: Restart systemd service
        if: ${{ vars.RESTART_SERVICE == 'true' }}
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🔁 Restarting tarot-bot systemd service"
            sudo systemctl restart tarot-bot.service
